package com.darood.app;

import android.content.Context;

/** Run against the Android preference doubles generated by first-launch.test.ps1. */
public class ArabicFontTest {
    public static void main(String[] args) {
        Context context = new Context();
        check(AppSettings.getArabicFont(context).equals("amiri"));
        for (String code : new String[]{"amiri", "scheherazade", "lateef", "notonaskh", "indopak"}) {
            AppSettings.saveArabicFont(context, code);
            AppSettings.initializeLaunchPreferences(context);
            check(AppSettings.getArabicFont(context).equals(code));
            check(AppSettings.isValidArabicFont(code));
            for (int size : new int[]{16, 24, 32}) {
                AppSettings.saveArabicFontSize(context, size);
                check(AppSettings.getArabicFontSize(context) == size);
                check(AppSettings.getArabicFont(context).equals(code));
            }
        }
        check(AppSettings.arabicFontFamily("indopak").equals("IndoPakLocal"));
        check(AppSettings.arabicFontLabel("indopak").equals("IndoPak"));
        AppSettings.saveArabicFont(context, "invalid");
        check(AppSettings.getArabicFont(context).equals("indopak"));
        System.out.println("44 Arabic font preference checks passed (Android doubles).");
    }
    private static void check(boolean value) {
        if (!value) throw new AssertionError("Arabic font preference regression");
    }
}
